/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherSessionsRouteImport } from './routes/teacher.sessions'
import { Route as TeacherMaterialsRouteImport } from './routes/teacher.materials'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as StudentSessionsRouteImport } from './routes/student.sessions'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherSessionsRoute = TeacherSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSessionsRoute = StudentSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/sessions': typeof StudentSessionsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/sessions': typeof StudentSessionsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/sessions': typeof StudentSessionsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/student'
    | '/teacher'
    | '/admin/assignments'
    | '/admin/sessions'
    | '/admin/subjects'
    | '/admin/users'
    | '/student/assignments'
    | '/student/materials'
    | '/student/sessions'
    | '/teacher/assignments'
    | '/teacher/materials'
    | '/teacher/sessions'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/assignments'
    | '/admin/sessions'
    | '/admin/subjects'
    | '/admin/users'
    | '/student/assignments'
    | '/student/materials'
    | '/student/sessions'
    | '/teacher/assignments'
    | '/teacher/materials'
    | '/teacher/sessions'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/student'
    | '/teacher'
    | '/admin/assignments'
    | '/admin/sessions'
    | '/admin/subjects'
    | '/admin/users'
    | '/student/assignments'
    | '/student/materials'
    | '/student/sessions'
    | '/teacher/assignments'
    | '/teacher/materials'
    | '/teacher/sessions'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/sessions': {
      id: '/teacher/sessions'
      path: '/sessions'
      fullPath: '/teacher/sessions'
      preLoaderRoute: typeof TeacherSessionsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/materials': {
      id: '/teacher/materials'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof TeacherMaterialsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/sessions': {
      id: '/student/sessions'
      path: '/sessions'
      fullPath: '/student/sessions'
      preLoaderRoute: typeof StudentSessionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentSessionsRoute: typeof StudentSessionsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentSessionsRoute: StudentSessionsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherMaterialsRoute: typeof TeacherMaterialsRoute
  TeacherSessionsRoute: typeof TeacherSessionsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherMaterialsRoute: TeacherMaterialsRoute,
  TeacherSessionsRoute: TeacherSessionsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
